## ubuntu xenial need for Python >= 3.7
dist: xenial 
# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.7

# Install the codecov pip dependency
install:
  - pip install -r ./requirements.txt
  - pip install codecov 
  - python setup.py install

# Run the unit test
script:
  - export CODECOV_TOKEN="e00c5f99-4f96-4cae-9bbc-d77668302050"
  - coverage run ./demo/test.py

# Push the results back to codecov
after_success:
  - codecov
