## ubuntu xenial need for Python >= 3.7
dist: xenial
# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies

# Install the codecov pip dependency
install:
  - pip install codecov
  - make install 

# Run the unit test
script:
  - export CODECOV_TOKEN="e00c5f99-4f96-4cae-9bbc-d77668302050"
  - cd test
  - coverage run ./test.py

# Push the results back to codecov
after_success:
  - codecov
